config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'

  resources :messages, only: [:create]
  
  resources :messages , except: [:index, :new]
  

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  name       :string
#  body       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  age        :integer
#

class Message < ActiveRecord::Base
  validates :name, length: {maximum: 20}, presence: true
  validates :body, length: {minimum: 2, miximum: 50}, presence: true
  validates :age,  numericality: { only_integer: true, greater_than_or_equal_to: 0}, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :message_params, :only => [:create]
  before_action :set_message, only: [:edit, :update, :destroy]
  protect_from_forgery with: :null_session
  
  def index
     @messages = Message.all
     @message = Message.new
  end
  
  def edit
  end
  
  def update
    if @message.update(message_params)
      redirect_to root_path, notice: 'メッセージを更新しました'
    else
      render 'edit'
    end
  end
  
  def create
    @message = Message.new(message_params)
    puts params
    if @message.save
      redirect_to root_path, notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかった時
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end

  private
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end
  
  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title MessageBoard
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet" /
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 
  body
    nav.navbar
      .container
        .navbar-header
          = link_to "MessageBoard", root_path, :class=>"navbar-brand"
    .container
      - if notice
        .alert.alert-info
          = notice
      = yield

app/views/messages/_form.html.slim
.row
  p#message-navi こちらからメッセージを送ってください。
  =form_for @message, :html => {class: "form-horizontal"}  do |f|
    - if @message.errors.present?
      .alert.alert-danger
        = alert
        ul 
          - @message.errors.full_messages.each do |full_message|
            li =full_message 
    .form-group
      = f.label :name, :class => "col-md-2 control-label"
        | 名前：
      .col-md-10
        = f.text_field :name, :class => "form-control", :placeholder => "名前：仮名士郎", :value => @message.name
    .form-group
      = f.label :age, :class => "col-md-2 control-label"
        | 年齢：
      .col-md-10
        = f.number_field :age, :class => "form-control", :placeholder => "18", :value => @message.age
    .form-group
      = f.label :body, :class => "col-md-2 control-label"
        | 内容：
      .col-md-10
        = f.text_area :body, :class => "form-control", :placeholder => "メッセージを入力：今度、鎌倉にでも遊びに行きましょう", :value => @message.body
    .form-group
      .col-md-offset-2.col-md-10
        = f.submit :class=>"btn btn-sm btn-primary", :id=>"message-submit", :value=>"作成"

app/views/messages/edit.html.slim
= render 'form'

app/views/messages/index.html.slim
.row
  .panel.panel-default
    .panel-heading
      | メッセージ一覧
    .panel-body
      table.table
        thead
          tr
            th#message-name 投稿名
            th#message-age 年齢
            th#message-body 内容
            th#messave-action 操作
        - @messages.each do |message|
          tbody
            tr
              th
                span.label.label-info
                  = message.name
              td = message.age
              td = message.body
              td
                button.btn.btn-default
                  = link_to "edit", edit_message_path(message)
                button.btn.btn-warning
                  = link_to "destroy", message, method: :delete, data: { confirm: '削除してもよろしいですか？'} 

= render 'form'